runtime: php
env: flex

runtime_config:
  document_root: public
  enable_stackdriver_integration: true

skip_files:
  - .env

env_variables:
  LOG_CHANNEL: stackdriver
  APP_KEY: base64:OIfQ4bjsfm/9l3jTVpMMWp9faCPI1/jf9RYFXXrvuyg=